### ISSUE TITLE
upgradinatorr.py - Error occurred while executing task SeriesSearch: Series with ID 0 does not exist

### ISSUE THREAD

**Issue by janusloo** [Drazzilb08/userScripts#61]
Hi thank you so much for this awesome script! I have configured it to upgrade my movies and tv's and followed the trash guide to set up my Radarr and Sonarr instances for good quality materials.

When I run upgradinatorr.py, Radarr works well. It will start looking for movies. However, I got this exception in Sonarr:
```

NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.IndexerSearch.SeriesSearchService.Execute (NzbDrone.Core.IndexerSearch.SeriesSearchCommand message) [0x00000] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\IndexerSearch\SeriesSearchService.cs:30 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <69ada62907b24213a012734531df1db1>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41
```

I have Sonarr configured as follows:
sonarr:
    - name: sonarr_1
      count: 5
      monitored: true
      status:
        - continuing
        - ended
      tag_name: checked
      unattended: true
      reset: false

What can be the cause of the exception? Thanks in advance!

**Comment by Drazzilb08** [comment]
🤔
This is interesting. I've never seen this one before.

Can you please provide logs in debug mode?

**Comment by janusloo** [comment]
Hi thanks for the quick reply. I already turned on DEBUG mode in Sonarr. Just ran the cut-off script again and got the following error:

`2023-11-08 08:59:09.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
2023-11-08 08:59:09.5|Debug|Api|[GET] /api/v3/series: 200.OK (107 ms)
2023-11-08 08:59:09.5|Debug|Api|[GET] /api/v3/tag: 200.OK (1 ms)
2023-11-08 08:59:09.6|Debug|SeriesService|Updating 5 series
2023-11-08 08:59:09.6|Debug|SeriesService|5 series updated
2023-11-08 08:59:09.6|Debug|Api|[PUT] /api/v3/series/editor: 202.Accepted (40 ms)
2023-11-08 08:59:09.6|Debug|Api|[GET] /api/system/status?apikey=(removed) 200.OK (1 ms)
2023-11-08 08:59:09.7|Debug|Api|[POST] /api/v3/command: 201.Created (25 ms)
2023-11-08 08:59:09.8|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
2023-11-08 08:59:09.8|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2023-11-08 08:59:09.8|Error|CommandExecutor|Error occurred while executing task SeriesSearch

[v3.0.10.1567] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.IndexerSearch.SeriesSearchService.Execute (NzbDrone.Core.IndexerSearch.SeriesSearchCommand message) [0x00000] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\IndexerSearch\SeriesSearchService.cs:30 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x0008b] in <69ada62907b24213a012734531df1db1>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2023-11-08 08:59:16.9|Debug|Api|[GET] /api/v3/command: 200.OK (13 ms)
2023-11-08 08:59:16.9|Debug|Api|[GET] /api/v3/system/task: 200.OK (41 ms)
2023-11-08 08:59:20.5|Debug|Api|[GET] /api/v3/log?page=1&pageSize=50&sortDirection=descending&sortKey=time: 200.OK (328 ms)
2023-11-08 08:59:26.3|Debug|Api|[GET] /api/v3/log/file: 200.OK (16 ms)`

What extra info do you need to troubleshoot this issue? I don't know how to use Trash's discord so please give me any info to connect there. Thanks in advance!

**Comment by Drazzilb08** [comment]
I need debug logs from the script. Not sonarr

https://trash-guides.info/discord

This should direct you to his discord

Also the issue was for upgradinatorr and not for cut-off right?

However, a copy of your config and your debug logs from the script will help.

**Comment by Drazzilb08** [comment]
Well I can duplicate on a different machine. I'll have to dig into this more. I'll update you when I have a solution.

**Comment by Drazzilb08** [comment]
Fixed with commit 2c90e4c

**Comment by janusloo** [comment]
Thank you so much for fixing this. I have just pulled the updated version. Tested it but the error is still there in Sonarr. This is the debug output log (I omitted the movies and series titles):

> ****************************************
> *        Script Input Validated        *
> ****************************************
> *********** Script Settings ************
> Dry_run: False
> Log Level: debug
> ****************************************
> 
> ****************************************
> Script Settings for radarr_1:
> count: 5
> tag_name: checked
> reset: False
> unattended: True
> status: released
> monitored: True
> ****************************************
> ****************************************
> *               radarr_1               *
> ****************************************
> *************** Settings ***************
> Instance Name: radarr_1
> URL: http://synonas.internal:7878
> api: ***************************84bca
> Connected to Radarr v5.0.3.8127 at http://synonas.internal:7878
> Tag Name: checked exists with tagId: 1, no need to create.
> Add tag payload: {'movieIds': [34, 35, 36, 37, 38], 'tags': [1], 'applyTags': 'add'}
> Search payload: {'name': 'MoviesSearch', 'movieIds': [34, 35, 36, 37, 38]}
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Total Movies: 728, Tagged Movies: 25 (3.43%), Untagged Movies: 703 (96.57%)
> 
> ****************************************
> Script Settings for sonarr_1:
> count: 5
> tag_name: checked
> reset: False
> unattended: True
> status: ['continuing', 'ended']
> monitored: True
> ****************************************
> ****************************************
> *               sonarr_1               *
> ****************************************
> *************** Settings ***************
> Instance Name: sonarr_1
> URL: http://synonas.internal:8989
> api: ***************************2d06e
> Connected to Sonarr v3.0.10.1567 at http://synonas.internal:8989
> Tag Name: checked exists with tagId: 1, no need to create.
> Add tag payload: {'seriesIds': [71, 72, 75, 76, 78], 'tags': [1], 'applyTags': 'add'}
> Search payload: {'name': 'SeriesSearch', 'seriesIds': [71, 72, 75, 76, 78]}
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Search request sent for '', this item has been tagged with 'checked'
> Total Series: 49, Tagged Series: 25 (51.02%), Untagged Series: 24 (48.98%)
> 

Sonarr error:

> NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
>   at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
>   at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
>   at NzbDrone.Core.IndexerSearch.SeriesSearchService.Execute (NzbDrone.Core.IndexerSearch.SeriesSearchCommand message) [0x00000] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\IndexerSearch\SeriesSearchService.cs:30 
>   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
>   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
>   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x0011e] in <69ada62907b24213a012734531df1db1>:0 
>   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
>   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41

**Comment by janusloo** [comment]
Hi thank you for the quick response but I am still having the same problem.
Please see
https://github.com/Drazzilb08/userScripts/issues/61#issuecomment-1803346843.
Thanks in advance!
